# https://github.com/P3TERX/ActionsVM

name: Ubuntu (ngrok)

on:
  workflow_dispatch:

jobs:
  Instance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Run Start Script
      run: source ubuntu-start.sh

    - name: Start SSH via ngrok
      uses: P3TERX/ssh2actions@main
      with:
        mode: ngrok
      env:
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
        NGROK_REGION: jp
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    - name: Run End Script
      run: source ubuntu-end.sh

    - name: Check if Folder is Empty
      id: check_folder
      run: |
        if [ "$(ls -A ./outdir)" ]; then
          echo "Folder is not empty"
          echo "::set-output name=folder_not_empty::true"
        else
          echo "Folder is empty"
          echo "::set-output name=folder_not_empty::false"
        fi
    
    - name: Upload Folder
      uses: actions/upload-artifact@v4
      if: steps.check_folder.outputs.folder_not_empty == 'true'
      with:
        name: out
        path: ./outdir
